### ISSUE TITLE
Fork multyvac

### ISSUE THREAD

**Issue by rgbkrk** [cloudpipe/cloudpipe#17]
As we went along implementing what level of spec we could glean, there are some known limitations of multyvac:
- Doesn't support Python 3, which is too bad because pickling has gotten more advanced
- Fails at pickling Pandas DataFrames
- Built under a different time, with different assumptions (now we have Docker!)
- The source is not open
- There are no signs that point to multyvac ever coming online

**Comment by rgbkrk** [comment]
Welp, I got multyvac to crap out on a simple job that submitted too quickly:

```python
import multyvac
import os

api_url = os.environ['CLOUDPIPE_URL']
multyvac.config.set_key(api_key=os.environ['OS_USERNAME'],
                        api_secret_key=os.environ['OS_PASSWORD'],
                        api_url=api_url)

print(multyvac.get(multyvac.shell_submit('ls -la')).get_result())
```

```python-traceback
Traceback (most recent call last):
  File "pi.py", line 12, in <module>
    print(multyvac.get(multyvac.shell_submit('ls -la')).get_result())
  File "/usr/local/lib/python2.7/site-packages/multyvac/job.py", line 342, in shell_submit
    return r['jids'][0]
KeyError: 'jids'
```

I'll look into this later, but I think there needs to be better handling on multyvac's side.

**Comment by rgbkrk** [comment]
Weird. Sometimes. `multyvac.shell_submit('ls -la')` gets back `jids` and sometimes it doesn't. Guess I'll need to dig into that.

**Comment by rgbkrk** [comment]
```
In [1]: %run pi.py
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/kyle6475/go/src/github.com/rgbkrk/cloudpipe-rackspace-demo/pi.py in <module>()
     10                         api_url=api_url)
     11
---> 12 jid = multyvac.shell_submit('ls -la')
     13 print(jid)
     14

/usr/local/lib/python2.7/site-packages/multyvac/job.pyc in shell_submit(self, cmd, _name, _core, _multicore, _layer, _vol, _env, _result_source, _result_type, _max_runtime, _profile, _restartable, _tags, _depends_on, _stdin)
    340                                data=payload,
    341                                content_type_json=True)
--> 342         return r['jids'][0]
    343
    344     def _get_auto_module_volume_name(self):

KeyError: 'jids'

In [2]: !cat pi.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import multyvac
import os

api_url = os.environ.get('CLOUDPIPE_URL', 'http://api.cloudpi.pe/v1/')
multyvac.config.set_key(api_key=os.environ['OS_USERNAME'],
                        api_secret_key=os.environ['OS_PASSWORD'],
                        api_url=api_url)

jid = multyvac.shell_submit('ls -la')
print(jid)



In [3]: %paste
import multyvac
import os

api_url = os.environ.get('CLOUDPIPE_URL', 'http://api.cloudpi.pe/v1/')
multyvac.config.set_key(api_key=os.environ['OS_USERNAME'],
                        api_secret_key=os.environ['OS_PASSWORD'],
                        api_url=api_url)

jid = multyvac.shell_submit('ls -la')
print(jid)

## -- End pasted text --
12
```

**Comment by rgbkrk** [comment]
On a separate note, make sure to use `fig rm -v` instead of `fig rm` so you don't have loose volumes abound.
